[package]
name = "robox"
version = "0.1.0"
authors = ["d1hasib <d1hasib@yahoo.com>"]
edition = "2018"
description = "A talking Robot"
readme = "README.md"
repository = "https://github.com/d1hasib/robox"
license-file = "LICENSE"

[dependencies]
structopt = "0.3"
colored = "1.9"
